POST http://localhost:3001/api/product
Content-Type: application/json

{
    "idProduct":"1",
    "product":[
        {
            "nameProduct":"test1",
            "price":1,
            "imgProduct":"test",
            "dateAdded":"2024-04-26",
            "idType":5,
            "brand":"test"
        }
    ],
    "tableName":"storage",
    "detail":[
        {
            "connectionprotocol":"test1",
            "capacitylevels":"1TB",
            "size":"test"
        }
    ] 
}

###

PATCH http://localhost:3001/api/product
Content-Type: application/json

{
    "idProduct":1,
    "product":[
        {
            "price":840
        }
    ],
    "tableName":"laptop",
    "detail":[
        {
            "sizeInch":15.6
        }
    ]
}

###

PATCH http://localhost:3001/api/product/sale
Content-Type: application/json

{
    "idSale":1,
    "sale":[
        {
            "title":"Sale Event"
        }
    ],
    "listId":[3,4,8,9,11,14,18,21],
    "detail":[
        {
            "discount":3
        }
    ]
}


###
POST http://localhost:3001/auth/login/admin
Content-Type: application/json

{
    "username":"admin",
    "password":"thisispasswordforadmin"
}

###
POST http://localhost:3001/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRmYXN0MTciLCJpYXQiOjE3MTU1MTc2MTksImV4cCI6MTcxNTUxODIxOX0.HtIVcNWH4f-A6r62Ya3y3hOZiHNMM5hbow3FRlqt5Vs

###
POST http://localhost:3001/auth/forgot
Content-Type: application/json

{
    "username":"dfast17",
    "mail":"d.phat1753@gmail.com"
}

###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "username":"dfast1705",
    "password":"dfast170",
    "email":"dfast170503@gmail.com"
}